### ISSUE TITLE
AcquireTokenByAuthorizationCodeAsync always returns empty acesstoken.

### ISSUE THREAD

**Issue by victormarante** [chrispadgettlivecom/WebApp-OpenIDConnect-DotNetCore21#1]
Hi, thanks for providing a good solution for .NET Core 2.1, when Microsoft is lacking behind.
I have a question though; When you acquire token, it always returns a AuthenticationResult where the AccessToken property is empty. Is this supposed to happen, or have done something wierd?

**Comment by chrispadgettlivecom** [comment]
Hi @victormarante 

I believe the application configuration in the **fabrikamb2c** tenant has been updated which is causing the access token to be set to `null`.

I'll follow the tenant owner up about this.
